replicaCount: 1

image:
  repository: ""
  pullPolicy: Always

service:
  enable: false
  type: ClusterIP
  port: 80

metrics:
  path: /prometheus
  group: nginx

logs:
  parser: nginx

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
   #cpu: 100m
   memory: 1Gi
  requests:
   #cpu: 100m
   memory: 1Gi
env:
  open:
    SERVER_NAME: mdm-admin-front.itdev.quanyou.com.cn
